'use client';

import { useEffect, useState } from 'react';
import { logger } from '@/lib/utils/logger';

/**
 * Custom hook to access CSP nonce for dynamic script/style loading
 *
 * The nonce is provided by the server via a header and should be used
 * for any dynamically generated scripts or styles to comply with CSP.
 *
 * This is particularly important for:
 * - Inline scripts generated by React
 * - Dynamic style injection
 * - Third-party library integration
 * - Three.js script loading
 */
export function useCSPNonce(): string | null {
  const [nonce, setNonce] = useState<string | null>(null);

  useEffect(() => {
    // Check if nonce is available in a meta tag (server-side rendered)
    const metaNonce = document.querySelector('meta[name="csp-nonce"]')?.getAttribute('content');

    if (metaNonce) {
      setNonce(metaNonce);
      return;
    }

    // Fallback: Fetch nonce from server if not in meta tag
    const fetchNonce = async () => {
      try {
        const response = await fetch('/api/security/csp-nonce', {
          method: 'GET',
          credentials: 'include',
        });

        if (response.ok) {
          const data = await response.json();
          if (data.nonce) {
            setNonce(data.nonce);
          }
        }
      } catch (error) {
        logger.warn('Failed to fetch CSP nonce:', error);
        // CSP nonce is optional for development
        if (process.env.NODE_ENV === 'development') {
          setNonce('dev-nonce-fallback');
        }
      }
    };

    fetchNonce();
  }, []);

  return nonce;
}

/**
 * Hook to create script elements with proper CSP nonce
 */
export function useCSPScript() {
  const nonce = useCSPNonce();

  const createScript = (
    src: string,
    attributes: Record<string, string> = {}
  ): HTMLScriptElement => {
    const script = document.createElement('script');
    script.src = src;

    // Add nonce if available
    if (nonce) {
      script.nonce = nonce;
    }

    // Add other attributes
    Object.entries(attributes).forEach(([key, value]) => {
      script.setAttribute(key, value);
    });

    return script;
  };

  const loadScript = async (
    src: string,
    attributes: Record<string, string> = {}
  ): Promise<void> => {
    return new Promise((resolve, reject) => {
      const script = createScript(src, attributes);

      script.onload = () => resolve();
      script.onerror = () => reject(new Error(`Failed to load script: ${src}`));

      document.head.appendChild(script);
    });
  };

  return {
    nonce,
    createScript,
    loadScript,
    isReady: nonce !== null,
  };
}

/**
 * Hook to create style elements with proper CSP nonce
 */
export function useCSPStyle() {
  const nonce = useCSPNonce();

  const createStyle = (css: string): HTMLStyleElement => {
    const style = document.createElement('style');
    style.textContent = css;

    // Add nonce if available
    if (nonce) {
      style.nonce = nonce;
    }

    return style;
  };

  const injectStyle = (css: string): HTMLStyleElement => {
    const style = createStyle(css);
    document.head.appendChild(style);
    return style;
  };

  return {
    nonce,
    createStyle,
    injectStyle,
    isReady: nonce !== null,
  };
}

/**
 * Utility function to add nonce to inline event handlers (if absolutely necessary)
 * Note: Inline event handlers should be avoided in favor of addEventListener
 */
export function getCSPAttributes(nonce?: string | null): Record<string, string> {
  const actualNonce =
    nonce ??
    (typeof window !== 'undefined'
      ? document.querySelector('meta[name="csp-nonce"]')?.getAttribute('content')
      : null);

  return actualNonce ? { nonce: actualNonce } : {};
}
